-- 코드를 입력하세요
SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, '%Y-%m-%d') OUT_DATE,
IF(OUT_DATE IS NULL, '출고미정', IF('2022-05-01' < OUT_DATE, '출고대기', '출고완료')) 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID ASC;