-- 코드를 입력하세요 --
SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) SALES
FROM PRODUCT P JOIN OFFLINE_SALE O USING (PRODUCT_ID)
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;










-- LEFT(PRODUCT_CODE, 2) PC, PRICE
-- SELECT * FROM OFFLINE_SALE GROUP BY PRODUCT_ID;
-- GROUP BY PRODUCT_ID;