-- 코드를 입력하세요
# SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL) TOTAL_SALES
# FROM (
    # ) TS JOIN AUTHOR USING (AUTHOR_ID)
# GROUP BY CATEGORY, AUTHOR_ID
# ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

# SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
# FROM AUTHOR JOIN (SELECT AUTHOR_ID, CATEGORY, SUM(TOTAL) TOTAL_SALES
# FROM (SELECT BOOK_ID, CATEGORY, AUTHOR_ID, SUM(PRICE * SALES) TOTAL FROM BOOK NATURAL JOIN BOOK_SALES GROUP BY BOOK_ID, AUTHOR_ID) T
# GROUP BY AUTHOR_ID, CATEGORY) TS USING (AUTHOR_ID)
# ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM AUTHOR JOIN (SELECT AUTHOR_ID, CATEGORY, SUM(TOTAL) TOTAL_SALES
FROM (SELECT BOOK_ID, CATEGORY, AUTHOR_ID, PRICE * SALES TOTAL FROM BOOK NATURAL JOIN BOOK_SALES WHERE SALES_DATE LIKE '2022-01%') TS
GROUP BY AUTHOR_ID, CATEGORY) TTS USING(AUTHOR_ID)
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;


# GROUP BY BOOK_ID, AUTHOR_ID) T
# GROUP BY AUTHOR_ID, CATEGORY) TS USING (AUTHOR_ID)
# ORDER BY AUTHOR_ID ASC, CATEGORY DESC;