-- 코드를 작성해주세요
SELECT DT.YEAR YEAR, (DT.MS - ED.SIZE_OF_COLONY) YEAR_DEV, ED.ID
FROM ECOLI_DATA ED JOIN (SELECT MAX(SIZE_OF_COLONY) MS, YEAR(DIFFERENTIATION_DATE) YEAR FROM ECOLI_DATA GROUP BY YEAR) DT ON YEAR(ED.DIFFERENTIATION_DATE) = DT.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;