-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO JOIN (SELECT * FROM FISH_NAME_INFO JOIN (SELECT FISH_TYPE, MAX(LENGTH) MAXLEN FROM FISH_INFO GROUP BY FISH_TYPE) M USING (FISH_TYPE)) ML USING (FISH_TYPE) WHERE FISH_INFO.LENGTH = ML.MAXLEN ORDER BY ID ASC;